apiVersion: v1
kind: ConfigMap
metadata:
  name: intellmeet-config
data:
  NODE_ENV: "production"
  CLIENT_URL: "https://intellmeet.local"
  MONGO_URL: "mongodb://mongodb:27017/intellmeet"
  REDIS_URL: "redis://redis:6379"
  PORT: "4000"
